QUESTIONS = {
	"Held hands romantically?" : .5,
	"Been on a date?" : .5,
	"Been in a relationship?" : .5,
	"Danced without leaving room for Jesus?" : .5,
	"Kissed a non-family member?" : .5,
	"Kissed a non-family member on the lips?" : .5,
	"French kissed?" : .7,
	"French kissed in public?" : 1,
	"Kissed on the neck?" : .8,
	"Kissed horizontally?" : 1,
	"Given or received a hickey?" : 1,
	"Kissed or been kissed on the breast?" : 2,
	"Kissed someone below the belt?" : 3,
	"Kissed for more than two hours consecutively?" : 2,
	"Played a game involving stripping?" : 2,
	"Seen or been seen by another person in a sensual context?" : 3,
	"Masturbated?" : 1,
	"Masturbated to a picture or video?" : 2,
	"Masturbated while someone else was in the room?" : 3,
	"Been caught masturbating?" : 3,
	"Masturbated with an inanimate object?" : 3,
	"Seen or read pornographic material?" : 3,
	"Massaged or been massaged sensually?" : 3,
	"Gone through the motions of intercourse while fully dressed?" : 4,
	"Undressed or been undressed by a MPS (member of the preferred sex)?" : 5,
	"Showered with a MPS?" : 5,
	"Fondled or had your butt cheeks fondled?": 5,
	"Fondled or had your breasts fondled?" : 5,
	"Fondled or had your genitals fondled?" : 5,
	"Had or given \"blue balls\"?" : 5,
	"Had an orgasm due to someone else's manipulation?" : 5,
	"Sent a sexually explicit text or instant message?" : 5,
	"Sent or received sexually explicit photographs?" : 5,
	"Engaged in sexually explicit activity over video chat?" : 5,
	"Cheated on a significant other during a relationship?" : 5,
	"Purchased contraceptives?" : 5,
	"Engaged in fellatio?" : 5,
	"Engaged in cunnilingus?" : 5,
	"Ingested someone else's genital secretion?" : 6,
	"Used a sex toy with a partner?" : 6,
	"Spent the night with a MPS?" : 5,
	"Been walked in on while engaging in a sexual act?" : 5.5,
	"Kicked a roommate out to commit a sexual act?" : 4.5,
	"Ingested alcohol in a non-religious context?": 2,
	"Played a drinking game?" : 3,
	"Been drunk?": 4,
	"Faked sobriety to parents or teachers?" : 4.5,
	"Had severe memory loss due to alcohol?": 6,
	"Used tobacco?" : 2.5,
	"Used marijuana?" : 3,
	"Used a drug stronger than marijuana?" : 4,
	"Used methamphetamine, crack cocaine, PCP, horse tranquilizers or heroin?" : 20,
	"Been sent to the office of a principal, dean or judicial affairs representative for a disciplinary infraction?" : .8,
	"Been put on disciplinary probation or suspended?" : 1.5,
	"Urinated in public?" : 2,
	"Gone skinny-dipping?": 3,
	"Gone streaking?" : 8,
	"Seen a stripper?": 8 ,
	"Had the police called on you?" : 6,
	"Run from the police?" : 10,
	"Had the police question you?" : 7,
	"Had the police handcuff you?" : 15,
	"Been arrested?" : 20,
	"Been convicted of a crime?" : 24,
	"Been convicted of a felony?": 28,
	"Committed an act of vandalism?" : 20,
	"Had sexual intercourse?" : 8,
	"Had sexual intercourse three or more times in one night?" : 16,
	"69?" : 14,
	"Had sexual intercourse 10 or more times?" : 20,
	"Had sexual intercourse in four or more positions?" : 10,
	"Had sexual intercourse with a stranger or person you met within 24 hours?" : 15,
	"Had sexual intercourse in a motor vehicle?" : 15,
	"Had sexual intercourse outdoors?" : 15,
	"Had sexual intercourse in public?" : 20,
	"Had sexual intercourse in a swimming pool or hot tub?" : 15,
	"Had sexual intercourse in a bed not belonging to you or your partner?" : 15,
	"Had sexual intercourse while you or your partner's parents were in the same home?" : 23,
	"Had sexual intercourse with non-participating third party in the same room?" : 25,
	"Joined the mile high club?" : 25,
	"Participated in a \"booty call\" with a partner whom you were not in a relationship with?" : 27,
	"Traveled 100 or more miles for the primary purpose of sexual intercourse?" : 35,
	"Had sexual intercourse with a partner with a 3 or more year age difference?" : 35,
	"Had sexual intercourse with a virgin?" : 15,
	"Had sexual intercourse without a condom?" : 20,
	"Had a STI test due to reasonable suspicion?" : 35,
	"Had a STI?": 40,
	"Had a threesome?": 25,
	"Attended an orgy?" : 35,
	"Had two or more distinct acts of sexual intercourse with two or more people within 24 hours?" : 35,
	"Had sexual intercourse with five or more partners?" : 35,
	"Been photographed or filmed during sexual intercourse by yourself or others?" : 40,
	"Had period sex?" : 40,
	"Had anal sex?" : 30,
	"Had a pregnancy scare?" : 40,
	"Impregnated someone or been impregnated?" : 40,
	"Paid or been paid for a sexual act?" : 50,
	"Committed an act of voyeurism?" : 30,
	"Committed an act of incest?" : 100,
	"Engaged in bestiality?" : 100,
}
